Traceback (most recent call last):
  File "rejectedplates.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "rejectedplates.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "rejectedplates.py", line 31, in <module>
    client.update_profile(description=bio)
AttributeError: 'Client' object has no attribute 'update_profile'
